// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gvnlnwzxnkuqdyfqnbjr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd2bmxud3p4bmt1cWR5ZnFuYmpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyNTMxNDUsImV4cCI6MjA1ODgyOTE0NX0.a7TZDb7rn2lWG1WMTKqCc7xpXtERNhtnVo3f90ECvwo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);